#pragma once

using namespace ATL;

template <class T>
class CProxy_IGMBAudioPlayerCOMObjEvents : public IConnectionPointImpl<T, &__uuidof( _IGMBAudioPlayerCOMObjEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
